:+1: Stop using `timeout` module which cause `TS2304`
```
[denops] Unexpected error occured in 'bcdice-api' (C:\home\develop\denops-bcdice-api.vim\denops\bcdice-api\main.ts): TypeError: TS2304 [ERROR]: Cannot find name 'window'.
[denops]   const promise = window.fetch(input, { signal, ...init })
[denops]                   ~~~~~~
[denops]     at https://deno.land/x/abortable@1.6/abort.ts:40:19
```

It's because `abortable` module used in `timeout` module does not support Worker environment