:package: Upgrade workerio to v1.3.1
From this commit, previous denops plugin does not work with the following error, due to the
protocol changes on workerio.

```
[denops] Plugin server is closed with error: TypeError: this[#remain].subarray is not a function
[denops]     at WorkerReader.readFromRemain (https://deno.land/x/workerio@v1.3.1/reader.ts:48:28)
[denops]     at WorkerReader.read (https://deno.land/x/workerio@v1.3.1/reader.ts:43:17)
[denops]     at async Module.iter (https://deno.land/x/std@0.93.0/io/util.ts:149:17)
[denops]     at async Decoder.decodeMultiAsync (https://deno.land/x/msgpack@v1.4/Decoder.ts:201:22)
[denops]     at async Session.listen (https://deno.land/x/msgpack_rpc@v3.1.0/session.ts:140:28)
```