:coffee: Use rhysd/action-setup-vim instead
Somehow, using thinca/action-setup-vim cause the following error
when we switched to Neovim v0.6.0 but rhysd/action-setup-vim

    Run thinca/action-setup-vim@v1
    with:
        vim_type: Neovim
        vim_version: v0.6.0
        gui: no
        download: available
        cache: true
        github_token: ***
    env:
        DENOPS_PATH: ./
        DENO_DIR: .deno
    Received 15888 of 15888 (100.0%), 0.9 MBs/sec
    Cache Size: ~0 MB (15888 B)
    /usr/bin/tar --use-compress-program zstd -d -xf /home/runner/work/_temp/6f915a28-92b7-4d9e-b567-056ad4815eb0/cache.tzst -P -C /home/runner/work/denops.vim/denops.vim
    Cache restored successfully
    Error: Target release not found

https://github.com/vim-denops/denops.vim/runs/4683219128?check_suite_focus=true